ws:
  al-api:
    host: https://v3.alapi.cn
    # replace to your key
    token: ENC(Novnrxv3g3gwTNz8ESmqZ9y2uamSLykjvPydUr8t+kJSLrE+T2VPfTUhhrnR8CYF)
spring:
  ai:
    mcp:
      server:
        version: ${project.version}
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    property:
      prefix: ENC(
      suffix: )
    # from command line
    password: fake-password

remote:
  feishu:
    app_id: replace-me
    app_secret: replace-me
    bi_table:
      app_token: ENC(9qbWkbHWWjhntK6Kgz5pYv/DC7l+qheJrNRaOctBqCUb8SE6jbszSwe7P4ns8tSl)
      inbox_table_id: ENC(ZhWSYX5uUkHLu4eVzemjIUew/IaPZJSjgPFCjH60Yqly2EK9K7rK1g==)
      key_table_id: ENC(Vg+rt4Dcu5sE7wi0DpLf4841rMgm1uvONMrqq/98DcJMoGwFXxFJzQ==)