spring:
  ai:
    mcp:
      client:
        sse:
          connections:
            mcp-server:
              url: http://localhost:8080
        stdio:
          connections:
            amap-maps:
              command: cmd
              args:
                - /c
                - npx
                - -y
                - "@amap/amap-maps-mcp-server"
              env:
                AMAP_MAPS_API_KEY: ENC(OxdeRXI3OfollKvFcfn5EKjloq9ZyH8bBX384JB3Tdp7TXvTDVGkexjmMbD/LcNooqBobNN0qLY=)
        name: mcp-client
        version: ${project.version}
    openai:
      base-url: https://api.deepseek.com
      api-key: ENC(iyG3/IJIW/GudIJuGpgO2P0CwK46pZC729rjwGmTVkBAtaWRSW01HVtrYxCc3p2Nk0k9CcTM+PE=)
      chat:
        options:
          model: deepseek-chat
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    property:
      prefix: ENC(
      suffix: )
    # from command line
    password: fake-password
server:
  port: 8888