spring:
  ai:
    mcp:
      client:
        sse:
          connections:
            mcp-server:
              url: http://localhost:8080
        name: mcp-client
        version: ${project.version}
    openai:
      base-url: https://api.deepseek.com
      api-key: ENC(iyG3/IJIW/GudIJuGpgO2P0CwK46pZC729rjwGmTVkBAtaWRSW01HVtrYxCc3p2Nk0k9CcTM+PE=)
      chat:
        options:
          model: deepseek-chat
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    property:
      prefix: ENC(
      suffix: )
    # from command line
    password: fake-password
server:
  port: 8888